name = "cloudpaste-backend"
main = "workers.js"
compatibility_date = "2023-05-18"

# 环境变量
[vars]
# 用于加密敏感配置的密钥
ENCRYPTION_SECRET = "lzl123456789987654321"

# 绑定D1数据库
# 需要替换为实际的数据库ID
[[d1_databases]]
binding = "DB"
database_name = "cloudpaste-db"
database_id = "f5682bc0-4f10-44bf-8c5a-e5923ab856f6"

# 本地开发时使用
[env.dev]
# 开发环境变量
[env.dev.vars]
ENCRYPTION_SECRET = "dev-encryption-secret-key"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "cloudpaste-db-dev"
database_id = "xxxxxxxxxxxxxxxxx" 
